# Generated by Django 4.1.4 on 2022-12-13 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_otpuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpuser',
            old_name='otp',
            new_name='otp_value',
        ),
    ]
